### ISSUE TITLE
How to use this application?

### ISSUE THREAD

**Issue by Necrobsd** [porovozls/django-telethon-authorization#1]
I use SQLite database. I wrote in django settings.py my TG_API_ID and TG_API_HASH but I dont understand what is TG_SESSION_PATH? Where can I get this session? If I fill this field with some path like os.path.join(BASE_DIR, 'some_file') I get error: "unable to open database file". In my django admin I see telegram authorization menu, but how to create new authorization and use it?

**Comment by ilkerkocatepe** [comment]
I want to open this topic :)

I need how to use this app.

Thanks
